# Stage I - structural MRI measurement differences of numerical variability

## Measurements

### Data Matrix Representation

For each measurement $m$ and region of interest (ROI) $r$, we obtain data from $n$ MCA repetitions across $m$ subject/visit pairs. These observations can be represented using the design matrix $\mathcal{M}_{m,r}$:

| MCA \ Subject/Visit | $sv_1$    | $sv_2$    | $\cdots$ | $sv_{m-1}$ | $sv_m$    | Anatomical $\rightarrow$ |
|----------------------|-----------|-----------|----------|------------|-----------|--------------------------|
| $rep_1$             | $x_{1,1}$ | $x_{1,2}$ | $\cdots$ | $x_{1,m-1}$| $x_{1,m}$ | $x_{1,:}$                |
| $rep_2$             | $x_{2,1}$ | $x_{2,2}$ | $\cdots$ | $x_{2,m-1}$| $x_{2,m}$ | $x_{2,:}$                |
| $\vdots$            | $\vdots$  | $\vdots$  | $\ddots$ | $\vdots$   | $\vdots$  | $\vdots$                 |
| $rep_{n-1}$         | $x_{n-1,1}$| $x_{n-1,2}$| $\cdots$| $x_{n-1,m-1}$| $x_{n-1,m}$| $x_{n-1,:}$          |
| $rep_n$             | $x_{n,1}$ | $x_{n,2}$ | $\cdots$ | $x_{n,m-1}$| $x_{n,m}$ | $x_{n,:}$                |
| Numerical $\downarrow$ | $x_{:,1}$ | $x_{:,2}$ | $\cdots$ | $x_{:,m-1}$| $x_{:,m}$ |                          |

Data matrix of size $n \times m$ with MCA repetitions as rows ($rep_1$ to $rep_n$) and subject/visit pairs as columns ($sv_1$ to $sv_m$). Each cell $x_{i,j}$ represents the measurement for subject/visit pair $j$ during MCA repetition $i$.

### Numerical Variability


Numerical variability quantifies the extent to which measurements for a given subject vary across MCA repetitions. For each subject/visit pair $j$, this variability is computed as:

$$\text{Var}_{\text{numerical}}^{(j)} = \frac{1}{n - 1} \sum_{i=1}^n \left(x_{i,j} - \bar{x}_{:,j}\right)^2, \quad \text{with } \bar{x}_{:,j} = \frac{1}{n} \sum_{i=1}^n x_{i,j}$$


The average numerical (intra-subject) variability across all subjects is:

$$\sigma^2_{num} = \frac{1}{m} \sum_{j=1}^m \text{Var}_{\text{numerical}}^{(j)}$$

### Anatomical Variability

#### General version

Anatomical variability quantifies differences between subjects within each MCA repetition. For each repetition $i$, it is computed as:

$$\text{Var}_{\text{anatomical}}^{(i)} = \frac{1}{m - 1} \sum_{j=1}^m \left(x_{i,j} - \bar{x}_{i,:}\right)^2, \quad \text{with } \bar{x}_{i,:} = \frac{1}{m} \sum_{j=1}^m x_{i,j}$$

The average anatomical (inter-subject) variability across all repetitions is:

$$\sigma^2_{anat} = \frac{1}{n} \sum_{i=1}^n \text{Var}_{\text{anatomical}}^{(i)}$$

#### IEEE referenced

One can also use IEEE obersvation instead of MCA repetitions. Anatomical variability is computed on IEEE value 

Here $\sigma^2_{anat}$ becomes

$$\sigma^2_{anat} = \text{Var}_{\text{anatomical}}^{(\text{IEEE})}$$

### Cohens'd coefficient

Let $X_1$ and $X_2$ represent two distinct populations with $|X_1|=N$, $|X_2|=M$. Cohen's d is defined as:
$$
d = \frac{\mu_1 - \mu_2}{\sigma_{\text{pooled}}},
$$
where $\mu_1$ and $\mu_2$ are the means of populations $X_1$ and $X_2$, respectively, and $\sigma_{\text{pooled}}$ is the pooled standard deviation given by:
$$
\sigma_{\text{pooled}} = \sqrt{\frac{(N-1)\sigma^{2}_{X_1} + (M-1)\sigma^{2}_{X_2}}{N + M - 2}}.
$$

### Anatomical vs Numerical Ratio

Let $\sigma_{anat}$ the anatomical variability and $\sigma_{num}$ the numerical variability.

$$r = \frac{\sigma_{num}}{\sigma_{anat}}$$

### Anatomical vs Numerical Ratio Pooled

Let $\sigma_{anat,pooled}$ the anatomical variability and $\sigma_{num,pooled}$ the numerical variability pooled between the HC and PD populations.

$$r = \frac{\sigma_{num,pooled}}{\sigma_{anat,pooled}}$$


### Anatomical vs Numerical Index

$$I = \frac{\sigma^2_{anat} - \sigma^2_{num}}{\sigma^2_{anat} + \sigma^2_{num}}$$

In [96]:
import pandas as pd
import os
import plotly.express as px
import numpy as np
from pathlib import Path

root_dir = Path(os.getcwd())
stats_dir = root_dir / "stats_QCed" / "sampled"
display(f"root directory: {root_dir.as_posix().split('VIP-python-client')[-1]}")
display(f"stats directory: {stats_dir.as_posix().split('VIP-python-client')[-1]}")

'root directory: /example/freesurfer-fuzzy/notebooks'

'stats directory: /example/freesurfer-fuzzy/notebooks/stats_QCed/sampled'

In [97]:
cohort = pd.read_csv("../cohort_stat.csv")
subjects = cohort["PATNO_id"].unique()
hc_subjects = cohort[cohort.dx_group == "HC"]["PATNO_id"].unique()
pd_subjects = cohort[cohort.dx_group != "HC"]["PATNO_id"].unique()

In [98]:
pd.read_parquet(stats_dir / "thickness.parquet")

,subjects,G_and_S_frontomargin_thickness,G_and_S_occipital_inf_thickness,G_and_S_paracentral_thickness,G_and_S_subcentral_thickness,G_and_S_transv_frontopol_thickness,G_and_S_cingul-Ant_thickness,G_and_S_cingul-Mid-Ant_thickness,G_and_S_cingul-Mid-Post_thickness,G_cingul-Post-dorsal_thickness,...,S_precentral-sup-part_thickness,S_suborbital_thickness,S_subparietal_thickness,S_temporal_inf_thickness,S_temporal_sup_thickness,S_temporal_transverse_thickness,MeanThickness_thickness,BrainSegVolNotVent,eTIV,hemi
0,sub-100005_ses-BL,2.341,2.383,2.414,2.612,2.466,2.615,2.533,2.420,2.701,...,2.503,2.151,2.259,2.457,2.542,2.166,2.49300,1359340.0,1.782154e+06,lh
1,sub-100005_ses-V04,2.291,2.420,2.418,2.564,2.485,2.587,2.548,2.492,2.760,...,2.514,2.191,2.245,2.451,2.536,2.110,2.48527,1352753.0,1.788384e+06,lh
2,sub-100006_ses-BL,2.084,2.388,2.370,2.708,2.370,2.462,2.478,2.595,2.662,...,2.240,2.180,2.248,2.343,2.299,2.705,2.40575,1028079.0,1.419119e+06,lh
3,sub-100006_ses-V04,2.140,2.298,2.353,2.626,2.495,2.518,2.430,2.595,2.639,...,2.236,2.264,2.186,2.268,2.262,2.761,2.37784,1023184.0,1.294401e+06,lh
4,sub-100007_ses-BL,2.328,2.331,2.470,2.615,2.697,2.570,2.467,2.396,2.651,...,2.563,2.262,2.345,2.456,2.418,2.115,2.42163,1196921.0,1.705678e+06,lh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,sub-75149_ses-V10,2.163,2.292,2.043,2.456,2.662,2.414,2.412,2.246,2.782,...,2.191,1.947,2.662,2.240,2.262,1.969,2.32658,966767.0,1.392304e+06,rh
599,sub-75479_ses-BL,2.077,2.110,2.226,2.563,2.100,2.471,2.370,2.366,2.944,...,2.105,2.567,2.355,1.991,2.157,2.521,2.26901,897239.0,1.243574e+06,rh
600,sub-75479_ses-V06,2.452,2.359,2.255,2.689,2.519,2.624,2.694,2.591,2.771,...,2.522,2.619,2.236,2.491,2.520,2.584,2.54014,982505.0,1.364436e+06,rh
601,sub-75480_ses-V06,2.084,2.287,2.203,2.395,2.229,2.494,2.420,2.419,2.813,...,2.025,1.977,2.313,2.333,2.340,2.104,2.25285,1015146.0,1.494210e+06,rh
602,sub-75480_ses-V10,2.097,2.365,2.330,2.451,2.273,2.483,2.477,2.424,2.718,...,2.018,2.001,2.242,2.511,2.353,2.281,2.24290,1008316.0,1.507983e+06,rh

In [99]:
def compute_numerical_variability_cortical_metric(metric, population):

    df = pd.read_parquet(f"{stats_dir}/{metric}.parquet")
    df = df[df["subjects"].isin(population)]
    Card = df.subjects.nunique()
    display(f"Number unique subjects in population: {Card}")
    numerical = (
        df.groupby(["subjects", "hemi"])
        .var()
        .reset_index()
        .drop(columns=["subjects"])
        .groupby("hemi")
        .mean()
        .reset_index()
    )
    numerical = numerical.melt(id_vars=["hemi"], var_name="ROI", value_name="variance")
    numerical["ROI"] = numerical["ROI"].str.replace(f"_{metric}", "", regex=False)
    return Card, numerical


def compute_anatomical_variability_cortical_metric(metric, population):

    df = pd.read_parquet(f"{stats_dir}/{metric}.parquet")
    df = df[df["subjects"].isin(population)]
    card = len(df.subjects.unique())
    display(f"Number unique subjects in population: {card}")

    # Group by numerical repetition
    df_lh = df[df["hemi"] == "lh"].reset_index(drop=True)
    df_rh = df[df["hemi"] == "rh"].reset_index(drop=True)
    df_lh["Rank"] = (
        df_lh.sort_values(by=["subjects"]).rank(method="dense")["subjects"].astype(int)
    )
    df_rh["Rank"] = (
        df_rh.sort_values(by=["subjects"]).rank(method="dense")["subjects"].astype(int)
    )
    df = pd.concat([df_lh, df_rh], axis=0)
    df["Rep"] = df["Rank"]
    df["Rep"] = (
        df.groupby(["Rank", "hemi"])
        .rank(method="first")["Rep"]
        .reset_index()["Rep"]
        .astype(int)
    )

    # Compute the average among MCA repetition of variances across subjects
    anatomical = (
        df.drop(columns=["subjects"])
        .groupby(["Rep", "hemi"])
        .var()
        .reset_index()
        .groupby("hemi")
        .mean()
        .drop(columns=["Rep", "Rank"])
        .reset_index()
    )

    anatomical = anatomical.melt(
        id_vars=["hemi"], var_name="ROI", value_name="variance"
    )
    anatomical["ROI"] = anatomical["ROI"].str.replace(f"_{metric}", "", regex=False)

    return card, anatomical

## Numerical vs Anatomical Ratio

In [100]:
def compute_pooled_variance(card_1, population_1, card_2, population_2):
    assert(population_1.ROI.nunique() == population_2.ROI.nunique())
    assert(set(population_1.ROI.unique()) == set(population_2.ROI.unique()))

    variance_pooled = population_1.copy()
    variance_pooled['variance'] = (
        (card_1 - 1) * population_1["variance"]
        + (card_2 - 1) * population_2["variance"]
    ) / (card_1 + card_2 - 2)
    return variance_pooled

def compute_numerical_anatomical_ratio(
    numerical, anatomical, filename=None
):
    assert(numerical.ROI.nunique() == anatomical.ROI.nunique())
    assert(set(numerical.ROI.unique()) == set(anatomical.ROI.unique()))

    r_na = numerical.copy()
    r_na["r^2"] = numerical["variance"] / anatomical["variance"]
    r_na["r"] = r_na["r^2"].apply(np.sqrt)
    if filename:
        r_na.to_csv(filename, index=False)
    return r_na

### Cortical Thickness

#### Ratio

In [101]:
# numerical variability
card_numerical, var_numerical = compute_numerical_variability_cortical_metric("thickness", subjects)
# anatomical variability
card_anatomical, var_anatomical = compute_anatomical_variability_cortical_metric("thickness", subjects)
# compute the ratio
r_na = compute_numerical_anatomical_ratio(var_numerical, var_anatomical, filename="thickness_r_na.csv")
r_na

'Number unique subjects in population: 610'

'Number unique subjects in population: 610'

    hemi                    ROI      variance       r^2         r
0     lh   G_and_S_frontomargin  1.923474e-03  0.074025  0.272074
1     rh   G_and_S_frontomargin  2.872588e-03  0.091945  0.303224
2     lh  G_and_S_occipital_inf  1.247042e-03  0.039660  0.199148
3     rh  G_and_S_occipital_inf  1.305716e-03  0.035976  0.189673
4     lh    G_and_S_paracentral  1.535508e-03  0.048039  0.219178
..   ...                    ...           ...       ...       ...
149   rh          MeanThickness  1.952241e-04  0.021343  0.146092
150   lh     BrainSegVolNotVent  2.855619e+07  0.002275  0.047698
151   rh     BrainSegVolNotVent  2.855619e+07  0.002278  0.047730
152   lh                   eTIV  4.536705e+05  0.000015  0.003902
153   rh                   eTIV  4.536705e+05  0.000015  0.003905

[154 rows x 5 columns]

#### Ratio Pooled

In [102]:
# numerical variability
card_numerical_hc, var_numerical_hc = compute_numerical_variability_cortical_metric(
    "thickness", hc_subjects
)
card_anatomical_hc, var_anatomical_hc = compute_anatomical_variability_cortical_metric(
    "thickness", hc_subjects
)
# anatomical variability
card_numerical_pd, var_numerical_pd = compute_numerical_variability_cortical_metric(
    "thickness", pd_subjects
)
card_anatomical_pd, var_anatomical_pd = compute_anatomical_variability_cortical_metric(
    "thickness", pd_subjects
)
# compute the pooled variance
var_numerical_pooled = compute_pooled_variance(
    card_numerical_hc, var_numerical_hc, card_numerical_pd, var_numerical_pd
)
var_anatomical_pooled = compute_pooled_variance(
    card_anatomical_hc, var_anatomical_hc, card_anatomical_pd, var_anatomical_pd
)
# compute the ratio
r_na_pooled = compute_numerical_anatomical_ratio(
    var_numerical_pooled, var_anatomical_pooled, filename="thickness_r_na_pooled.csv"
)
r_na_pooled

'Number unique subjects in population: 206'

'Number unique subjects in population: 206'

'Number unique subjects in population: 404'

'Number unique subjects in population: 404'

    hemi                    ROI      variance       r^2         r
0     lh   G_and_S_frontomargin  1.923350e-03  0.073940  0.271920
1     rh   G_and_S_frontomargin  2.872201e-03  0.092177  0.303606
2     lh  G_and_S_occipital_inf  1.247085e-03  0.039654  0.199133
3     rh  G_and_S_occipital_inf  1.305809e-03  0.035996  0.189725
4     lh    G_and_S_paracentral  1.535452e-03  0.048057  0.219219
..   ...                    ...           ...       ...       ...
149   rh          MeanThickness  1.953154e-04  0.021370  0.146185
150   lh     BrainSegVolNotVent  2.856743e+07  0.002359  0.048572
151   rh     BrainSegVolNotVent  2.856743e+07  0.002365  0.048631
152   lh                   eTIV  4.540267e+05  0.000016  0.003971
153   rh                   eTIV  4.540267e+05  0.000016  0.003976

[154 rows x 5 columns]

#### Difference between pooled vs non-pooled

In [103]:
r_na_diff = r_na_pooled.copy()
r_na_diff["r"] = (r_na_diff["r"] - r_na["r"]).abs()
print(f"Max difference: {r_na_diff['r'].max()}")
px.scatter(
    r_na_diff,
    x="ROI",
    y="r",
    log_y=True,
    color="hemi",
    title="Numerical-Anatomical Ratio Absolute Difference between Pooled and Non-Pooled (Cortical Thickness)",
    labels={"r": "Numerical-Anatomical Ratio Difference"},
).update_yaxes(tickformat=".2e")

Max difference: 0.0024428477168456086

### Surface Area

#### Ratio

In [104]:
# numerical variability
card_numerical, var_numerical = compute_numerical_variability_cortical_metric("area", subjects)
# anatomical variability
card_anatomical, var_anatomical = compute_anatomical_variability_cortical_metric("area", subjects)
# compute the ratio
r_na = compute_numerical_anatomical_ratio(var_numerical, var_anatomical, filename="area_r_na.csv")
r_na

'Number unique subjects in population: 610'

'Number unique subjects in population: 610'

    hemi                    ROI      variance       r^2         r
0     lh   G_and_S_frontomargin  1.172174e+03  0.075397  0.274586
1     rh   G_and_S_frontomargin  1.095075e+03  0.111671  0.334171
2     lh  G_and_S_occipital_inf  1.826916e+03  0.050716  0.225201
3     rh  G_and_S_occipital_inf  1.223586e+03  0.049892  0.223365
4     lh    G_and_S_paracentral  1.260333e+03  0.065902  0.256713
..   ...                    ...           ...       ...       ...
149   rh          WhiteSurfArea  4.536331e+05  0.005920  0.076942
150   lh     BrainSegVolNotVent  2.855619e+07  0.002275  0.047697
151   rh     BrainSegVolNotVent  2.855619e+07  0.002278  0.047733
152   lh                   eTIV  4.536705e+05  0.000015  0.003902
153   rh                   eTIV  4.536705e+05  0.000015  0.003905

[154 rows x 5 columns]

#### Ratio Pooled

In [105]:
# numerical variability
card_numerical_hc, var_numerical_hc = compute_numerical_variability_cortical_metric(
    "area", hc_subjects
)
card_anatomical_hc, var_anatomical_hc = compute_anatomical_variability_cortical_metric(
    "area", hc_subjects
)
# anatomical variability
card_numerical_pd, var_numerical_pd = compute_numerical_variability_cortical_metric(
    "area", pd_subjects
)
card_anatomical_pd, var_anatomical_pd = compute_anatomical_variability_cortical_metric(
    "area", pd_subjects
)
# compute the pooled variance
var_numerical_pooled = compute_pooled_variance(
    card_numerical_hc, var_numerical_hc, card_numerical_pd, var_numerical_pd
)
var_anatomical_pooled = compute_pooled_variance(
    card_anatomical_hc, var_anatomical_hc, card_anatomical_pd, var_anatomical_pd
)
# compute the ratio
r_na_pooled = compute_numerical_anatomical_ratio(
    var_numerical_pooled, var_anatomical_pooled, filename="area_r_na_pooled.csv"
)
r_na_pooled

'Number unique subjects in population: 206'

'Number unique subjects in population: 206'

'Number unique subjects in population: 404'

'Number unique subjects in population: 404'

    hemi                    ROI      variance       r^2         r
0     lh   G_and_S_frontomargin  1.172137e+03  0.077498  0.278385
1     rh   G_and_S_frontomargin  1.095083e+03  0.114924  0.339004
2     lh  G_and_S_occipital_inf  1.826977e+03  0.050638  0.225028
3     rh  G_and_S_occipital_inf  1.223723e+03  0.050351  0.224389
4     lh    G_and_S_paracentral  1.260295e+03  0.065844  0.256601
..   ...                    ...           ...       ...       ...
149   rh          WhiteSurfArea  4.537565e+05  0.006077  0.077958
150   lh     BrainSegVolNotVent  2.856743e+07  0.002359  0.048571
151   rh     BrainSegVolNotVent  2.856743e+07  0.002364  0.048623
152   lh                   eTIV  4.540267e+05  0.000016  0.003971
153   rh                   eTIV  4.540267e+05  0.000016  0.003976

[154 rows x 5 columns]

#### Difference between pooled vs non-pooled

In [106]:
r_na_diff = r_na_pooled.copy()
r_na_diff["r"] = (r_na_diff["r"] - r_na["r"]).abs()
print(f"Max difference: {r_na_diff['r'].max()}")
px.scatter(
    r_na_diff,
    x="ROI",
    y="r",
    log_y=True,
    color="hemi",
    title="Numerical-Anatomical Ratio Absolute Difference between Pooled and Non-Pooled (Surface Area)",
    labels={"r": "Numerical-Anatomical Ratio Difference"},
).update_yaxes(tickformat=".2e")

Max difference: 0.009815702490734046

### Cortical Volume

#### Ratio

In [107]:
# numerical variability
card_numerical, var_numerical = compute_numerical_variability_cortical_metric("volume", subjects)
# anatomical variability
card_anatomical, var_anatomical = compute_anatomical_variability_cortical_metric("volume", subjects)
# compute the ratio
r_na = compute_numerical_anatomical_ratio(var_numerical, var_anatomical, filename="volume_r_na.csv")
r_na

'Number unique subjects in population: 610'

'Number unique subjects in population: 610'

    hemi                    ROI      variance       r^2         r
0     lh   G_and_S_frontomargin  1.102199e+04  0.100910  0.317664
1     rh   G_and_S_frontomargin  1.053152e+04  0.129980  0.360527
2     lh  G_and_S_occipital_inf  1.691184e+04  0.047470  0.217876
3     rh  G_and_S_occipital_inf  1.100807e+04  0.036569  0.191231
4     lh    G_and_S_paracentral  1.444572e+04  0.081958  0.286283
..   ...                    ...           ...       ...       ...
147   rh  S_temporal_transverse  1.547357e+03  0.150564  0.388026
148   lh     BrainSegVolNotVent  2.855619e+07  0.002275  0.047697
149   rh     BrainSegVolNotVent  2.855619e+07  0.002277  0.047721
150   lh                   eTIV  4.536705e+05  0.000015  0.003902
151   rh                   eTIV  4.536705e+05  0.000015  0.003904

[152 rows x 5 columns]

#### Ratio Pooled

In [108]:
# numerical variability
card_numerical_hc, var_numerical_hc = compute_numerical_variability_cortical_metric(
    "volume", hc_subjects
)
card_anatomical_hc, var_anatomical_hc = compute_anatomical_variability_cortical_metric(
    "volume", hc_subjects
)
# anatomical variability
card_numerical_pd, var_numerical_pd = compute_numerical_variability_cortical_metric(
    "volume", pd_subjects
)
card_anatomical_pd, var_anatomical_pd = compute_anatomical_variability_cortical_metric(
    "volume", pd_subjects
)
# compute the pooled variance
var_numerical_pooled = compute_pooled_variance(
    card_numerical_hc, var_numerical_hc, card_numerical_pd, var_numerical_pd
)
var_anatomical_pooled = compute_pooled_variance(
    card_anatomical_hc, var_anatomical_hc, card_anatomical_pd, var_anatomical_pd
)
# compute the ratio
r_na_pooled = compute_numerical_anatomical_ratio(
    var_numerical_pooled, var_anatomical_pooled, filename="volume_r_na_pooled.csv"
)
r_na_pooled

'Number unique subjects in population: 206'

'Number unique subjects in population: 206'

'Number unique subjects in population: 404'

'Number unique subjects in population: 404'

    hemi                    ROI      variance       r^2         r
0     lh   G_and_S_frontomargin  1.102158e+04  0.102617  0.320338
1     rh   G_and_S_frontomargin  1.053091e+04  0.133278  0.365072
2     lh  G_and_S_occipital_inf  1.691138e+04  0.047398  0.217711
3     rh  G_and_S_occipital_inf  1.100898e+04  0.036965  0.192263
4     lh    G_and_S_paracentral  1.444494e+04  0.082012  0.286378
..   ...                    ...           ...       ...       ...
147   rh  S_temporal_transverse  1.547367e+03  0.151059  0.388662
148   lh     BrainSegVolNotVent  2.856743e+07  0.002359  0.048571
149   rh     BrainSegVolNotVent  2.856743e+07  0.002366  0.048640
150   lh                   eTIV  4.540267e+05  0.000016  0.003971
151   rh                   eTIV  4.540267e+05  0.000016  0.003976

[152 rows x 5 columns]

#### Difference between pooled vs non-pooled

In [109]:
r_na_diff = r_na_pooled.copy()
r_na_diff["r"] = (r_na_diff["r"] - r_na["r"]).abs()
print(f"Max difference: {r_na_diff['r'].max()}")
px.scatter(
    r_na_diff,
    x="ROI",
    y="r",
    log_y=True,
    color="hemi",
    title="Numerical-Anatomical Ratio Absolute Difference between Pooled and Non-Pooled (Cortical Volume)",
    labels={"r": "Numerical-Anatomical Ratio Difference"},
).update_yaxes(tickformat=".2e")

Max difference: 0.007493994156117623

### Subcortical Volume

In [177]:
def compute_numerical_variability_subcortical_metric(metric, population):

    df = pd.read_parquet(f"{stats_dir}/{metric}.parquet")
    df = df[df["subjects"].isin(population)]
    Card = df.subjects.nunique()
    display(f"Number unique subjects in population: {Card}")
    numerical = (
        df.groupby(["subjects"])
        .var()
        .reset_index()
        .drop(columns=["subjects"])
        .mean()
        .reset_index()
    )
    numerical.rename(columns={"index": "ROI", 0:"variance"}, inplace=True)
    numerical["ROI"] = numerical["ROI"].str.replace(f"_{metric}", "", regex=False)
    return Card, numerical


def compute_anatomical_variability_subcortical_metric(metric, population):

    df = pd.read_parquet(f"{stats_dir}/{metric}.parquet")
    df = df[df["subjects"].isin(population)]
    card = len(df.subjects.unique())
    display(f"Number unique subjects in population: {card}")

    # Group by MCA repetition
    df["Rank"] = (
        df.sort_values(by=["subjects"])
        .rank(method="first")["subjects"]
        .astype(int)
        .reset_index(drop=True)
    )
    df["Rep"] = df["Rank"]
    df["Rep"] = (
        df.groupby("Rank")
        .rank(method="first")["Rep"]
        .astype(int)
    )

    # Compute the average among MCA repetition of variances across subjects
    anatomical = (
        df.drop(columns=["subjects","Rank"])
        .groupby(["Rep"])
        .var()
        .reset_index()
        .drop(columns=["Rep"])
        .mean()
        .reset_index()
    )
    anatomical.rename(columns={"index": "ROI", 0: "variance"}, inplace=True)
    anatomical["ROI"] = anatomical["ROI"].str.replace(f"_{metric}", "", regex=False)

    return card, anatomical

#### Ratio

In [178]:
# numerical variability
card_numerical, var_numerical = compute_numerical_variability_subcortical_metric(
    "subcortical_volume", subjects
)
# anatomical variability
card_anatomical, var_anatomical = compute_anatomical_variability_subcortical_metric(
    "subcortical_volume", subjects
)
# compute the ratio
r_na = compute_numerical_anatomical_ratio(
    var_numerical, var_anatomical, filename="thickness_r_na.csv"
)
r_na

'Number unique subjects in population: 600'

'Number unique subjects in population: 600'

                              ROI       variance       r^2         r
0          Left-Lateral-Ventricle    9732.550601  0.000115  0.010728
1               Left-Inf-Lat-Vent    1208.121442  0.007930  0.089050
2    Left-Cerebellum-White-Matter  193125.265333  0.044826  0.211722
3          Left-Cerebellum-Cortex  139076.759524  0.004365  0.066070
4                   Left-Thalamus   19876.859521  0.026490  0.162758
..                            ...            ...       ...       ...
59                MaskVol-to-eTIV       0.000003  0.001557  0.039454
60                 lhSurfaceHoles      66.177122  0.178211  0.422151
61                 rhSurfaceHoles      42.104411  0.150776  0.388299
62                   SurfaceHoles     120.269250  0.105416  0.324678
63  EstimatedTotalIntraCranialVol  461127.920188  0.000016  0.003949

[64 rows x 4 columns]

#### Ratio Pooled

In [179]:
# numerical variability
card_numerical_hc, var_numerical_hc = compute_numerical_variability_subcortical_metric(
    "subcortical_volume", hc_subjects
)
card_anatomical_hc, var_anatomical_hc = compute_anatomical_variability_subcortical_metric(
    "subcortical_volume", hc_subjects
)
# anatomical variability
card_numerical_pd, var_numerical_pd = compute_numerical_variability_subcortical_metric(
    "subcortical_volume", pd_subjects
)
card_anatomical_pd, var_anatomical_pd = (
    compute_anatomical_variability_subcortical_metric("subcortical_volume", pd_subjects)
)
# compute the pooled variance
var_numerical_pooled = compute_pooled_variance(
    card_numerical_hc, var_numerical_hc, card_numerical_pd, var_numerical_pd
)
var_anatomical_pooled = compute_pooled_variance(
    card_anatomical_hc, var_anatomical_hc, card_anatomical_pd, var_anatomical_pd
)
# compute the ratio
r_na_pooled = compute_numerical_anatomical_ratio(
    var_numerical_pooled,
    var_anatomical_pooled,
    filename="subcortical_volume_r_na_pooled.csv",
)
r_na_pooled

'Number unique subjects in population: 202'

'Number unique subjects in population: 202'

'Number unique subjects in population: 398'

'Number unique subjects in population: 398'

                              ROI       variance       r^2         r
0          Left-Lateral-Ventricle    9733.514027  0.000116  0.010783
1               Left-Inf-Lat-Vent    1208.164789  0.008286  0.091026
2    Left-Cerebellum-White-Matter  193158.875784  0.045850  0.214125
3          Left-Cerebellum-Cortex  139109.630833  0.004498  0.067070
4                   Left-Thalamus   19879.904446  0.028061  0.167515
..                            ...            ...       ...       ...
59                MaskVol-to-eTIV       0.000003  0.001652  0.040641
60                 lhSurfaceHoles      66.165483  0.164566  0.405667
61                 rhSurfaceHoles      42.078886  0.114316  0.338107
62                   SurfaceHoles     120.225049  0.088278  0.297116
63  EstimatedTotalIntraCranialVol  461497.793850  0.000017  0.004118

[64 rows x 4 columns]

#### Difference between pooled vs non-pooled

In [182]:
r_na_diff = r_na_pooled.copy()
r_na_diff["r"] = (r_na_diff["r"] - r_na["r"]).abs()
# Filter out ROI 
roi_to_keep = [
        "Left-Accumbens-area",
        "Left-Amygdala",
        "Left-Caudate",
        "Left-Hippocampus",
        "Left-Pallidum",
        "Left-Putamen",
        "Left-Thalamus",
        "Left-Lateral-Ventricle",
        "Right-Accumbens-area",
        "Right-Amygdala",
        "Right-Caudate",
        "Right-Hippocampus",
        "Right-Pallidum",
        "Right-Putamen",
        "Right-Thalamus",
        "Right-Lateral-Ventricle",
    ]
r_na_diff = r_na_diff[r_na_diff.ROI.isin(roi_to_keep)]
print(f"Max difference: {r_na_diff['r'].max()}")
px.scatter(
    r_na_diff,
    x="ROI",
    y="r",
    log_y=True,
    title="Numerical-Anatomical Ratio Absolute Difference between Pooled and Non-Pooled (Subcortical Volume)",
    labels={"r": "Numerical-Anatomical Ratio Difference"},
).update_yaxes(tickformat=".2e")

Max difference: 0.007641019570298058